// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD70oalgBuTApIFSKxFSeQV4DAkUe1CTjc',
    appId: '1:1042709870497:web:847aa0b847200398867de0',
    messagingSenderId: '1042709870497',
    projectId: 'moodmakeraccessibility',
    authDomain: 'moodmakeraccessibility.firebaseapp.com',
    storageBucket: 'moodmakeraccessibility.appspot.com',
    measurementId: 'G-JZY9712LVT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTYitIM0pdyHirpGJjodzr45vIYBj9YPk',
    appId: '1:1042709870497:android:796c4ffc1c15c924867de0',
    messagingSenderId: '1042709870497',
    projectId: 'moodmakeraccessibility',
    storageBucket: 'moodmakeraccessibility.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsHYKTdRcsdC2qZqL1pIjgzBCRNE7VrLQ',
    appId: '1:1042709870497:ios:2413053b19932696867de0',
    messagingSenderId: '1042709870497',
    projectId: 'moodmakeraccessibility',
    storageBucket: 'moodmakeraccessibility.appspot.com',
    iosBundleId: 'com.accessibilityx.memood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsHYKTdRcsdC2qZqL1pIjgzBCRNE7VrLQ',
    appId: '1:1042709870497:ios:3a96b17079e322aa867de0',
    messagingSenderId: '1042709870497',
    projectId: 'moodmakeraccessibility',
    storageBucket: 'moodmakeraccessibility.appspot.com',
    iosBundleId: 'com.example.moodMakerKp.RunnerTests',
  );
}
